---
- name: Add nginx repo
  apt_repository:
    repo: ppa:nginx/stable

- name: Install nginx
  apt:
    name: nginx
    state: present
    force: yes
    update_cache: yes

- name: Copy nginx config files
  copy:
    src: "{{ item }}"
    dest: /etc/nginx
    owner: "{{ deploy_user }}"
    group: "{{ deploy_group }}"
  with_items:
    - nginx.conf

- name: Create a directory if it does not exist
  file:
    path: "/etc/nginx/{{ item }}"
    state: directory
    owner: "{{ deploy_user }}"
    group: "{{ deploy_group }}"
    mode: 0644
  with_items:
    - sites-available
    - sites-enabled

- name: Copy nginx configuration 
  template:
    src: "{{ nginx_conf_template }}"
    dest: "/etc/nginx/sites-available/default"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_group }}"
    mode: 0644

- name: Symlink default site
  file: 
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    state: link

- name: Set nginx user
  lineinfile: 
    dest: /etc/nginx/nginx.conf
    regexp: "^user"
    line: "user {{ deploy_user }};"
    state: present
  notify:
    - Reload nginx
    - Restart nginx  
