---
- name: Detect rvm binary
  stat: path='{{ rvm_rvm }}'
  register: rvm_binary
  
- name: Detect rvm installer
  stat: path='{{ rvm_temp_download_path }}/rvm-installer.sh' 
  register: rvm_installer

- name: Detect current rvm version
  command: '{{ rvm_rvm }} --version'
  changed_when: False
  register: rvm_current_version
  when: rvm_binary.stat.exists

- name: Install rvm installer
  get_url:
    url: '{{ rvm_latest_installer }}'
    dest: '{{ rvm_temp_download_path }}/rvm-installer.sh'
  when: not rvm_installer.stat.exists

- name: Configure rvm installer
  file:
    path: '{{ rvm_temp_download_path }}/rvm-installer.sh'
    mode: 0755
  when: not rvm_binary.stat.exists

- name: Install rvm
  command: 'gpg --keyserver {{ rvm_gpg_key_server }} --recv-keys {{ rvm_gpg_keys }}'
  changed_when: False
  when: rvm_gpg_keys != ''
  become_user: '{{ rvm_user }}'

- name: Install rvm
  command: >
    {{ rvm_temp_download_path }}/rvm-installer.sh {{ rvm_version }}
    --path {{ rvm_install_path }} {{ rvm_install_flags }}
  when: not rvm_binary.stat.exists
  become_user: '{{ rvm_user }}'

- name: Configure rvm
  command: '{{ rvm_rvm }} autolibs {{ rvm_autolib_mode }}'
  when: not rvm_binary.stat.exists
  become_user: '{{ rvm_user }}'