---
- name: Ensure git is installed
  apt:
    name: git
    state: present

#{TODO} Create the release and current folders
- name: Clone git repositories
  git: 
    repo: git@bitbucket.org:codysseynepal/parking_frontend.git
    dest: "{{ deploy_user_path }}/{{ react_app_name }}"
    version: "{{ deploy_branch_react }}"
    accept_hostkey: yes
    force: yes
  tags: clone


